// ROLE: Метаданные (названия полей, единицы измерения, подсказки) для панели администратора.
export const NEW_SECTIONS: Record<string, { title: string; icon: string; old_sections: string[] }> = {
  world_network: {
    title: "World & Network",
    icon: "🌐",
    old_sections: ["world", "network"],
  },
  snake_physics: {
    title: "Snake & Physics",
    icon: "🐍",
    old_sections: ["snake", "simulation"],
  },
  food_boost: {
    title: "Food & Boost",
    icon: "🍎",
    old_sections: ["food", "boost"],
  },
  camera_visual: {
    title: "Camera & Visual",
    icon: "🎨",
    old_sections: ["visual"],
  },
};

export const getNewSectionKey = (oldSec: string): string => {
  if (oldSec === "world" || oldSec === "network") return "world_network";
  if (oldSec === "snake" || oldSec === "simulation") return "snake_physics";
  if (oldSec === "food" || oldSec === "boost") return "food_boost";
  return "camera_visual";
};

export const FIELD_LABELS: Record<string, string> = {
  width: "Map Width",
  height: "Map Height",
  target_food_count: "Target Food Count",
  food_overflow_limit: "Food Overflow Limit",
  cluster_count: "Cluster Count",
  cluster_spawn_chance: "Cluster Spawn Chance",
  cluster_spread: "Cluster Spread",
  cluster_move_chance: "Cluster Move Chance",
  tick_rate: "Server Tick Rate",
  base_speed_per_second: "Snake Base Speed",
  max_turn_speed_deg_per_second: "Max Turn Speed",
  min_turn_radius: "Min Turn Radius",
  turn_radius_thickness_coeff: "Turn Radius Thickness Coeff",
  turn_idle_smoothing_at_20hz: "Idle Alignment Smoothing",
  turn_active_smoothing_at_20hz: "Active Turn Smoothing",
  start_length: "Start Length",
  start_score: "Start Score",
  base_head_radius: "Min Head Radius",
  score_thickness_scale: "Thickness Growth per Score",
  camera_zoom_out_coeff: "Camera Zoom-Out Coeff",
  growth_score_per_segment: "Score per Growth Segment",
  min_body_length: "Min Body Length",
  safe_spawn_distance: "Safe Spawn Distance",
  max_growth_score: "Snake Max Growth Cap",
  min_score: "Min Boost Score",
  speed_multiplier: "Speed Multiplier",
  drain_interval_seconds: "Mass Drain Interval",
  drain_per_interval: "Mass Drain per Interval",
  food_drop_value: "Dropped Food Value",
  base_radius: "Base Food Radius",
  radius_value_scale: "Food Radius Scale",
  death_drop_score_fraction: "Death Drop Score Fraction",
  attraction_radius: "Food Attraction Radius",
  attraction_speed: "Food Attraction Speed",
  aoi_radius: "Base AoI Radius",
  aoi_length_padding: "AoI Length Bonus",
  min_fog_radius: "Min Fog Radius",
  fog_score_expansion_coeff: "Fog Expansion Coeff",
  camera_base_zoom: "Camera Base Zoom",
  camera_pitch_angle: "Camera Pitch Angle",
  camera_z_height: "Camera Z-Height",
  camera_y_offset: "Camera Y-Offset",
  mouse_sensitivity: "Mouse Sensitivity",
  head_glow_radius: "Head Glow Radius",
  portals_enabled: "Portals Enabled",
  portals_count: "Portal Pairs Count",
  portals_radius: "Portal Radius",
  portals_teleport_delay_ms: "Teleport Delay",
  portals_spawn_chance: "Portal Spawn Chance",
  portals_growth_time: "Portal Growth Time",
  black_holes_enabled: "Black Holes Enabled",
  black_holes_count: "Black Holes Count",
  black_holes_spawn_chance: "Black Hole Spawn Chance",
  black_holes_pull_radius: "Gravity Pull Radius",
  black_holes_pull_force: "Gravity Pull Force",
  black_holes_kill_radius: "Event Horizon Radius",
  black_holes_growth_time: "Black Hole Growth Time",
};

export const FIELD_UNITS: Record<string, string> = {
  width: "cells",
  height: "cells",
  target_food_count: "pcs",
  food_overflow_limit: "pcs",
  cluster_count: "pcs",
  cluster_spawn_chance: "fraction",
  cluster_spread: "cells",
  cluster_move_chance: "fraction",
  tick_rate: "Hz",
  base_speed_per_second: "cells/s",
  max_turn_speed_deg_per_second: "°/s",
  min_turn_radius: "cells",
  turn_radius_thickness_coeff: "coeff",
  turn_idle_smoothing_at_20hz: "coeff",
  turn_active_smoothing_at_20hz: "coeff",
  start_length: "segm",
  start_score: "points",
  base_head_radius: "cells",
  score_thickness_scale: "coeff",
  camera_zoom_out_coeff: "coeff",
  growth_score_per_segment: "formula",
  max_growth_score: "score",
  min_body_length: "segm",
  safe_spawn_distance: "cells",
  min_score: "points",
  speed_multiplier: "x",
  drain_interval_seconds: "sec",
  drain_per_interval: "points",
  food_drop_value: "points",
  base_radius: "cells",
  radius_value_scale: "coeff",
  death_drop_score_fraction: "fraction",
  attraction_radius: "cells",
  attraction_speed: "cells/s",
  aoi_radius: "cells",
  aoi_length_padding: "coeff",
  min_fog_radius: "cells",
  fog_score_expansion_coeff: "coeff",
  camera_base_zoom: "coeff",
  camera_pitch_angle: "°",
  camera_z_height: "cells",
  camera_y_offset: "cells",
  mouse_sensitivity: "coeff",
  head_glow_radius: "cells",
  portals_enabled: "0/1",
  portals_count: "pairs",
  portals_radius: "cells",
  portals_teleport_delay_ms: "ms",
  portals_spawn_chance: "chance",
  portals_growth_time: "sec",
  black_holes_enabled: "0/1",
  black_holes_count: "slots",
  black_holes_spawn_chance: "chance",
  black_holes_pull_radius: "cells",
  black_holes_pull_force: "cells/s",
  black_holes_kill_radius: "cells",
  black_holes_growth_time: "sec",
};

export const HIDDEN_FIELDS = new Set(["types", "aoi_radius", "aoi_length_padding"]);

export const FIELD_TOOLTIPS: Record<string, string> = {
  target_food_count: "Target food count that the server maintains on the map.",
  food_overflow_limit: "Maximum extra food above target, after which the server trims excess food.",
  cluster_spawn_chance: "Chance (0 to 1) of spawning new food inside a dense cluster rather than randomly.",
  cluster_move_chance: "Chance of shifting a food cluster center, checked by the server once every minute.",
  tick_rate: "Frequency of game world updates (ticks per second) on the server.",
  turn_radius_thickness_coeff: "Coefficient for increasing the turn radius based on the snake's thickness.",
  turn_idle_smoothing_at_20hz: "Smoothness of return to straight motion when keys are released.",
  turn_active_smoothing_at_20hz: "Smoothness of entering a turn when keys are pressed.",
  score_thickness_scale: "Coefficient for scaling body thickness and head radius relative to score.",
  camera_zoom_out_coeff: "Camera zoom-out scaling factor as the player's length increases.",
  growth_score_per_segment: "Required score to grow a segment. Can be a number or formula (e.g. '10 + l * 0.5').",
  max_growth_score: "Score limit above which the snake stops growing new body segments.",
  drain_interval_seconds: "Time interval in seconds at which score is drained during acceleration.",
  food_drop_value: "Value of food particles dropped behind the snake during acceleration.",
  attraction_radius: "Attraction (magnetism) radius within which food flies towards the snake.",
  attraction_speed: "Speed of food attraction towards the snake's head.",
  min_fog_radius: "Minimum visual fog-of-war radius around the snake's head.",
  fog_score_expansion_coeff: "Fog-of-war expansion coefficient relative to score.",
  mouse_sensitivity: "Cursor deflection factor from the center of the screen to reach max turning speed.",
  head_glow_radius: "Radius of the warm glow effect around the snake's head.",
  portals_enabled: "Enable/disable spatial teleportation portal pairs on the map.",
  portals_count: "Number of active portal pairs.",
  portals_radius: "Radius of the portal area in grid units.",
  portals_teleport_delay_ms: "Delay in milliseconds before the snake emerges from the output portal.",
  portals_spawn_chance: "Probability checked once per minute for each slot to spawn a portal.",
  portals_growth_time: "Duration in seconds for a portal to smoothly grow or collapse.",
  black_holes_enabled: "Enable/disable gravity-well black holes.",
  black_holes_count: "Number of active black hole slots on the map.",
  black_holes_spawn_chance: "Probability checked once per minute to spawn a black hole.",
  black_holes_pull_radius: "Drift/gravity field range.",
  black_holes_pull_force: "Gravity pull strength factor.",
  black_holes_kill_radius: "Event horizon range.",
  black_holes_growth_time: "Duration in seconds for a black hole to smoothly grow or collapse."
};
